import type { RideCategoryCode, RideCategoryDefinition } from './types.js';

const DEFAULT_RADIUS = [800, 1500, 2500, 4000, 6500, 10000];
const LARGE_RADIUS = [1200, 2500, 4000, 6500, 10000, 15000];

function cat(partial: RideCategoryDefinition): RideCategoryDefinition {
  return partial;
}

export const RIDE_CATEGORIES: RideCategoryDefinition[] = [
  cat({
    code: 'moto',
    name: 'Moto',
    description: 'Deslocamento rápido para 1 passageiro com bagagem leve.',
    passengerLimitMin: 1,
    passengerLimitMax: 1,
    isShared: false,
    isPremium: false,
    isPassengerRide: true,
    requiresScheduling: false,
    driverRequirements: {
      minRating: 4.6,
      maxCancellationRate: 0.12,
      minAge: 21,
      requiresEar: true,
      requiresDefensiveTraining: true,
      notes: 'CNH com observação de atividade remunerada',
    },
    vehicleRequirements: {
      summary: 'Motocicleta 125–300cc, ano mínimo móvel 10 anos, licenciamento vigente',
      minEngineCc: 125,
      maxEngineCc: 300,
      minYearOffset: 10,
    },
    acceptanceRules: 'Sem bagagem volumosa; fora de áreas restritas; bloqueio em chuva forte conforme município',
    baggagePolicy: 'Mochila e bolsa pequena; proibida mala média/grande',
    tariffMultipliers: { base: 0.72, distance: 0.78, time: 0.74, minimum: 0.7 },
    specificMultipliers: { weather_risk_light: 1.05, weather_risk_moderate: 1.15, airport_pickup: 1.0 },
    dynamicCap: 1.8,
    searchRadiusStagesM: [600, 1200, 2000, 3500, 5500, 8000],
    offerTimeoutSeconds: 6,
    takeRateBpsMin: 1800,
    takeRateBpsMax: 2400,
    driverDynamicShareBps: 7500,
  }),
  cat({
    code: 'economico',
    name: 'Econômico',
    description: 'Categoria padrão para corridas imediatas e agendadas.',
    passengerLimitMin: 1,
    passengerLimitMax: 4,
    isShared: false,
    isPremium: false,
    isPassengerRide: true,
    requiresScheduling: false,
    driverRequirements: { minRating: 4.5, minAcceptanceRate: 0.45, maxCancellationRate: 0.15, requiresEar: true },
    vehicleRequirements: {
      summary: 'Hatch ou sedã compacto, 4 portas, A/C, ano mínimo móvel 12 anos, 4 lugares',
      minSeats: 4,
      minYearOffset: 12,
      requiresAc: true,
      bodyTypes: ['hatch', 'sedan_compact'],
    },
    acceptanceRules: 'Distribuição primária; aceita corrida imediata, agendada e bagagem normal',
    baggagePolicy: 'Até 1 mala média ou 2 pequenas',
    tariffMultipliers: { base: 1.0, distance: 1.0, time: 1.0, minimum: 1.0 },
    specificMultipliers: { shared_penalty: -0.08, corporate_discount_eligibility: false },
    dynamicCap: 2.2,
    searchRadiusStagesM: DEFAULT_RADIUS,
    offerTimeoutSeconds: 8,
    takeRateBpsMin: 1800,
    takeRateBpsMax: 2400,
    driverDynamicShareBps: 7500,
  }),
  cat({
    code: 'comfort',
    name: 'Comfort',
    description: 'Veículos mais recentes com padrão superior de conforto.',
    passengerLimitMin: 1,
    passengerLimitMax: 4,
    isShared: false,
    isPremium: true,
    isPassengerRide: true,
    requiresScheduling: false,
    driverRequirements: {
      minRating: 4.75,
      minCompletedRides: 300,
      maxCancellationRate: 0.1,
      notes: 'Inspeção interna de conforto aprovada',
    },
    vehicleRequirements: {
      summary: 'Sedã, hatch premium ou crossover; A/C; ano mínimo móvel 8 anos',
      minSeats: 4,
      minYearOffset: 8,
      requiresAc: true,
      bodyTypes: ['sedan', 'hatch_premium', 'crossover'],
    },
    acceptanceRules: 'Somente motoristas elegíveis; bloqueio por nota de conforto baixa',
    baggagePolicy: 'Até 2 malas médias ou 1 grande + 1 pequena',
    tariffMultipliers: { base: 1.24, distance: 1.2, time: 1.18, minimum: 1.22 },
    specificMultipliers: { service_quality_bonus: 1.03, airport_pickup: 1.08 },
    dynamicCap: 2.5,
    searchRadiusStagesM: DEFAULT_RADIUS,
    offerTimeoutSeconds: 6,
    takeRateBpsMin: 2000,
    takeRateBpsMax: 2700,
    driverDynamicShareBps: 7800,
  }),
  cat({
    code: 'executivo',
    name: 'Executivo',
    description: 'Atendimento premium para viagens corporativas e aeroportuárias.',
    passengerLimitMin: 1,
    passengerLimitMax: 4,
    isShared: false,
    isPremium: true,
    isPassengerRide: true,
    requiresScheduling: false,
    driverRequirements: {
      minRating: 4.82,
      minCompletedRides: 700,
      minAcceptanceRate: 0.55,
      requiresExecutiveTraining: true,
    },
    vehicleRequirements: {
      summary: 'Sedã médio ou superior, interior premium, dual-zone preferencial, ano mínimo 7 anos',
      minSeats: 4,
      minYearOffset: 7,
      requiresAc: true,
      bodyTypes: ['sedan', 'sedan_executive'],
    },
    acceptanceRules: 'Prioridade corporativa/aeroportuária; validação rígida de conservação',
    baggagePolicy: 'Até 2 malas grandes ou 3 médias',
    tariffMultipliers: { base: 1.45, distance: 1.38, time: 1.34, minimum: 1.42 },
    specificMultipliers: { airport_pickup: 1.12, corporate_priority_bonus: 1.05 },
    dynamicCap: 2.8,
    searchRadiusStagesM: DEFAULT_RADIUS,
    offerTimeoutSeconds: 6,
    takeRateBpsMin: 2000,
    takeRateBpsMax: 2700,
    driverDynamicShareBps: 7800,
  }),
  cat({
    code: 'black',
    name: 'Black',
    description: 'Sedã premium de alto padrão para clientes exigentes.',
    passengerLimitMin: 1,
    passengerLimitMax: 4,
    isShared: false,
    isPremium: true,
    isPassengerRide: true,
    requiresScheduling: false,
    driverRequirements: {
      minRating: 4.88,
      minCompletedRides: 1200,
      maxCancellationRate: 0.08,
      requiresPremiumTraining: true,
    },
    vehicleRequirements: {
      summary: 'Sedã premium preto ou cor homologada, ano mínimo 6 anos, acabamento impecável',
      minSeats: 4,
      minYearOffset: 6,
      requiresAc: true,
      bodyTypes: ['sedan_premium'],
    },
    acceptanceRules: 'Bloqueio por reprovação de acabamento; prioridade alta reputação/corporativo premium',
    baggagePolicy: 'Até 2 malas grandes',
    tariffMultipliers: { base: 1.82, distance: 1.65, time: 1.58, minimum: 1.75 },
    specificMultipliers: {
      reputation_priority_bonus: 1.08,
      airport_pickup: 1.15,
      event_demand_cap_bonus: 0.1,
    },
    dynamicCap: 3.0,
    searchRadiusStagesM: DEFAULT_RADIUS,
    offerTimeoutSeconds: 6,
    takeRateBpsMin: 2000,
    takeRateBpsMax: 2700,
    driverDynamicShareBps: 7800,
  }),
  cat({
    code: 'suv',
    name: 'SUV',
    description: 'Grupos, bagagem volumosa ou viagens aeroportuárias.',
    passengerLimitMin: 1,
    passengerLimitMax: 6,
    isShared: false,
    isPremium: true,
    isPassengerRide: true,
    requiresScheduling: false,
    driverRequirements: { minRating: 4.8, minCompletedRides: 500, maxCancellationRate: 0.1 },
    vehicleRequirements: {
      summary: 'SUV ou minivan homologada, ano mínimo 8 anos, mínimo 6 passageiros',
      minSeats: 6,
      minYearOffset: 8,
      bodyTypes: ['suv', 'minivan'],
    },
    acceptanceRules: 'Quando passageiros > 4, bagagem volumosa, aeroporto ou preferência explícita',
    baggagePolicy: 'Até 4 malas médias ou 2 grandes + 2 pequenas',
    tariffMultipliers: { base: 1.68, distance: 1.5, time: 1.42, minimum: 1.55 },
    specificMultipliers: { extra_capacity: 1.1, airport_pickup: 1.14 },
    dynamicCap: 2.8,
    searchRadiusStagesM: DEFAULT_RADIUS,
    offerTimeoutSeconds: 8,
    takeRateBpsMin: 2000,
    takeRateBpsMax: 2700,
    driverDynamicShareBps: 7500,
  }),
  cat({
    code: 'pet',
    name: 'Pet',
    description: 'Transporte de animais com motorista e veículo preparados.',
    passengerLimitMin: 1,
    passengerLimitMax: 4,
    isShared: false,
    isPremium: false,
    isPassengerRide: true,
    requiresScheduling: false,
    driverRequirements: { minRating: 4.65, requiresPetTraining: true, notes: 'Aceite explícito para animais' },
    vehicleRequirements: {
      summary: 'Capa protetora, kit de limpeza, espaço adequado, ano mínimo 10 anos',
      minSeats: 4,
      minYearOffset: 10,
      requiresPetReady: true,
    },
    acceptanceRules: 'Pet informado na solicitação; animal agressivo sem contenção bloqueia',
    baggagePolicy: 'Itens do pet liberados; caixa de transporte recomendada',
    tariffMultipliers: { base: 1.18, distance: 1.1, time: 1.08, minimum: 1.16 },
    specificMultipliers: { cleaning_risk: 1.06, large_pet: 1.1 },
    dynamicCap: 2.3,
    searchRadiusStagesM: DEFAULT_RADIUS,
    offerTimeoutSeconds: 8,
    takeRateBpsMin: 1800,
    takeRateBpsMax: 2400,
    driverDynamicShareBps: 7500,
  }),
  cat({
    code: 'entrega',
    name: 'Entrega',
    description: 'Envio de pacotes sem passageiro embarcado.',
    passengerLimitMin: 0,
    passengerLimitMax: 0,
    isShared: false,
    isPremium: false,
    isPassengerRide: false,
    requiresScheduling: false,
    driverRequirements: { minRating: 4.5, notes: 'Sem histórico recente de extravio ou fraude' },
    vehicleRequirements: { summary: 'Compartimento compatível; baú homologado para motos; sem cargas perigosas' },
    acceptanceRules: 'Sem passageiro; validação de peso/volume; itens ilícitos proibidos',
    baggagePolicy: 'Modelado como pacote com peso máximo por veículo',
    tariffMultipliers: { base: 0.96, distance: 1.02, time: 0.82, minimum: 0.92 },
    specificMultipliers: { fragile_item: 1.08, priority_delivery: 1.18 },
    dynamicCap: 2.0,
    searchRadiusStagesM: DEFAULT_RADIUS,
    offerTimeoutSeconds: 10,
    takeRateBpsMin: 1800,
    takeRateBpsMax: 2400,
    driverDynamicShareBps: 7500,
  }),
  cat({
    code: 'aeroporto',
    name: 'Aeroporto',
    description: 'Modalidade aeroportuária sobre categoria-base elegível.',
    passengerLimitMin: 1,
    passengerLimitMax: 4,
    isShared: false,
    isPremium: true,
    isPassengerRide: true,
    requiresScheduling: false,
    inheritsBaseCategory: 'economico',
    driverRequirements: { minRating: 4.7, minCompletedRides: 250, requiresAirportTraining: true },
    vehicleRequirements: {
      summary: 'Econômico, Comfort, Executivo, Black ou SUV elegível com porta-malas funcional',
      minSeats: 4,
    },
    acceptanceRules: 'Fila virtual georreferenciada; regras por terminal; taxa aeroportuária',
    baggagePolicy: 'Capacidade reforçada conforme viagem',
    tariffMultipliers: { base: 1.22, distance: 1.0, time: 1.0, minimum: 1.22 },
    specificMultipliers: { terminal_congestion_min: 1.05, terminal_congestion_max: 1.18, airport_queue_bonus_driver: 1.04 },
    dynamicCap: 2.6,
    searchRadiusStagesM: DEFAULT_RADIUS,
    offerTimeoutSeconds: 6,
    takeRateBpsMin: 2000,
    takeRateBpsMax: 2700,
    driverDynamicShareBps: 7500,
  }),
  cat({
    code: 'corporativo',
    name: 'Corporativo',
    description: 'Viagens B2B com faturamento empresarial.',
    passengerLimitMin: 1,
    passengerLimitMax: 4,
    isShared: false,
    isPremium: true,
    isPassengerRide: true,
    requiresScheduling: false,
    inheritsBaseCategory: 'comfort',
    driverRequirements: { minRating: 4.78, maxCancellationRate: 0.09, requiresB2bBilling: true },
    vehicleRequirements: { summary: 'Comfort, Executivo, Black ou Econômico homologado pela empresa' },
    acceptanceRules: 'Centro de custo obrigatório; política de horários e teto por corrida',
    baggagePolicy: 'Herdado da categoria-base',
    tariffMultipliers: { base: 1.0, distance: 1.0, time: 1.0, minimum: 1.0 },
    specificMultipliers: { sla_priority: 1.06, driver_priority_bonus: 1.03, corporate_discount_min: 0.9, corporate_discount_max: 0.98 },
    dynamicCap: 2.0,
    searchRadiusStagesM: DEFAULT_RADIUS,
    offerTimeoutSeconds: 6,
    takeRateBpsMin: 2000,
    takeRateBpsMax: 2700,
    driverDynamicShareBps: 7500,
  }),
  cat({
    code: 'van',
    name: 'Van',
    description: 'Transporte coletivo leve para grupos.',
    passengerLimitMin: 1,
    passengerLimitMax: 12,
    isShared: false,
    isPremium: false,
    isPassengerRide: true,
    requiresScheduling: true,
    driverRequirements: { minRating: 4.75, requiresEar: true, requiresCollectiveTraining: true },
    vehicleRequirements: {
      summary: 'Van homologada, vistoria específica, cintos para todos os assentos',
      minSeats: 12,
    },
    acceptanceRules: 'Origem/destino compatíveis; peso de bagagem controlado; grupo ou shuttle',
    baggagePolicy: 'Até 1 mala média por passageiro ou regra contratual',
    tariffMultipliers: { base: 2.2, distance: 1.88, time: 1.72, minimum: 2.05 },
    specificMultipliers: { group_coordination: 1.06, airport_shuttle: 1.1 },
    dynamicCap: 2.5,
    searchRadiusStagesM: LARGE_RADIUS,
    offerTimeoutSeconds: 15,
    takeRateBpsMin: 1500,
    takeRateBpsMax: 2200,
    driverDynamicShareBps: 7500,
  }),
  cat({
    code: 'micro_onibus',
    name: 'Micro-ônibus',
    description: 'Fretamento leve e transfer para grupos grandes.',
    passengerLimitMin: 1,
    passengerLimitMax: 24,
    isShared: false,
    isPremium: false,
    isPassengerRide: true,
    requiresScheduling: true,
    driverRequirements: { minRating: 4.8, requiresCollectiveTraining: true, notes: 'Habilitação e certificações locais' },
    vehicleRequirements: { summary: 'Micro-ônibus documentado, rastreamento e vistoria reforçada', minSeats: 24 },
    acceptanceRules: 'Agendamento preferencial; bloqueio de corrida imediata sem operação dedicada',
    baggagePolicy: 'Conforme compartimento ou contrato',
    tariffMultipliers: { base: 3.1, distance: 2.35, time: 2.1, minimum: 2.9 },
    specificMultipliers: { reservation: 1.08, large_group: 1.12 },
    dynamicCap: 2.3,
    searchRadiusStagesM: LARGE_RADIUS,
    offerTimeoutSeconds: 20,
    takeRateBpsMin: 1500,
    takeRateBpsMax: 2200,
    driverDynamicShareBps: 7500,
  }),
  cat({
    code: 'compartilhado',
    name: 'Transporte Compartilhado',
    description: 'Viagem compartilhada com desvio limitado.',
    passengerLimitMin: 1,
    passengerLimitMax: 2,
    isShared: true,
    isPremium: false,
    isPassengerRide: true,
    requiresScheduling: false,
    driverRequirements: { minRating: 4.68, minAcceptanceRate: 0.5 },
    vehicleRequirements: { summary: 'Econômico ou Comfort homologado, mínimo 4 assentos', minSeats: 4 },
    acceptanceRules: 'Rota com pares compatíveis; limite de desvio; bloqueio para bagagem grande',
    baggagePolicy: 'Pequenas e médias leves; malas grandes bloqueiam',
    tariffMultipliers: { base: 0.84, distance: 0.86, time: 0.92, minimum: 0.8 },
    specificMultipliers: { detour_discount_min: -0.18, detour_discount_max: -0.05, occupancy_gain_bonus_driver: 1.04 },
    dynamicCap: 1.8,
    searchRadiusStagesM: DEFAULT_RADIUS,
    offerTimeoutSeconds: 10,
    takeRateBpsMin: 1800,
    takeRateBpsMax: 2400,
    driverDynamicShareBps: 7500,
  }),
  cat({
    code: 'pcd',
    name: 'Transporte Adaptado (PCD)',
    description: 'Atendimento inclusivo com veículo adaptado.',
    passengerLimitMin: 1,
    passengerLimitMax: 5,
    isShared: false,
    isPremium: false,
    isPassengerRide: true,
    requiresScheduling: false,
    driverRequirements: { minRating: 4.75, requiresPcdTraining: true },
    vehicleRequirements: {
      summary: 'Adaptação homologada para cadeira de rodas ou necessidade informada',
      requiresWheelchairAccess: true,
      minSeats: 3,
    },
    acceptanceRules: 'Preferência alta; bloqueio se veículo não atender necessidade declarada',
    baggagePolicy: 'Cadeira, andador e itens assistivos não contam como bagagem tarifável',
    tariffMultipliers: { base: 1.36, distance: 1.22, time: 1.28, minimum: 1.3 },
    specificMultipliers: { assistance_time: 1.08, priority_match_weight_bonus: 0.1 },
    dynamicCap: 1.9,
    searchRadiusStagesM: LARGE_RADIUS,
    offerTimeoutSeconds: 10,
    takeRateBpsMin: 1800,
    takeRateBpsMax: 2400,
    driverDynamicShareBps: 7500,
  }),
];

const byCode = new Map(RIDE_CATEGORIES.map((c) => [c.code, c]));

export function getCategory(code: RideCategoryCode): RideCategoryDefinition | undefined {
  return byCode.get(code);
}

export function listCategories(filter?: { passengerRidesOnly?: boolean; activeOnly?: boolean }) {
  let list = [...RIDE_CATEGORIES];
  if (filter?.passengerRidesOnly) list = list.filter((c) => c.isPassengerRide);
  return list;
}

export function getPublicCategory(c: RideCategoryDefinition) {
  return {
    code: c.code,
    name: c.name,
    description: c.description,
    passengerLimitMin: c.passengerLimitMin,
    passengerLimitMax: c.passengerLimitMax,
    isShared: c.isShared,
    isPremium: c.isPremium,
    isPassengerRide: c.isPassengerRide,
    requiresScheduling: c.requiresScheduling,
    baggagePolicy: c.baggagePolicy,
    acceptanceRules: c.acceptanceRules,
    driverRequirements: c.driverRequirements,
    vehicleRequirements: c.vehicleRequirements,
    tariffMultipliers: c.tariffMultipliers,
    dynamicCap: c.dynamicCap,
  };
}
